name: open-gira
channels:
  - conda-forge
  - defaults
dependencies:
  - pyarrow=6.0.0
  - tqdm=4.62.3
  - pytest=6.2.4
  - pip
  - pip:
    - nismod-snail==0.2.1
    - osmium==3.2.0
    - snakemake==6.10.0
